export const PakistanCities = [
  { value: 'Islamabad', label: 'Islamabad' },
  { value: 'Rawalpindi', label: 'Rawalpindi' },
  { value: 'Lahore', label: 'Lahore' },
  { value: 'Karachi', label: 'Karachi' },
  { value: 'Peshawar', label: 'Peshawar' },
  { value: 'Quetta', label: 'Quetta' },
  { value: 'Multan', label: 'Multan' },
  { value: 'Faisalabad', label: 'Faisalabad' },
  { value: 'Sialkot', label: 'Sialkot' },
  { value: 'Gujranwala', label: 'Gujranwala' },
  { value: 'Sargodha', label: 'Sargodha' },
  { value: 'Sahiwal', label: 'Sahiwal' },
  { value: 'Bahawalpur', label: 'Bahawalpur' },
  { value: 'Sheikhupura', label: 'Sheikhupura' },
  { value: 'Rahim Yar Khan', label: 'Rahim Yar Khan' },
  { value: 'Gujrat', label: 'Gujrat' },
  { value: 'Jhang', label: 'Jhang' },
  { value: 'Wah', label: 'Wah' },
  { value: 'Mandi Bahauddin', label: 'Mandi Bahauddin' },
  { value: 'Kasur', label: 'Kasur' },
  { value: 'Okara', label: 'Okara' },
  { value: 'Mianwali', label: 'Mianwali' },
  { value: 'Sukkur', label: 'Sukkur' },
  { value: 'Larkana', label: 'Larkana' },
  { value: 'Hyderabad', label: 'Hyderabad' },
  { value: 'Mirpur Khas', label: 'Mirpur Khas' },
  { value: 'Kamoke', label: 'Kamoke' },
  { value: 'Khanewal', label: 'Khanewal' },
  { value: 'Dera Ghazi Khan', label: 'Dera Ghazi Khan' },
  { value: 'Mardan', label: 'Mardan' },
  { value: 'Dera Ismail Khan', label: 'Dera Ismail Khan' },
  { value: 'Kohat', label: 'Kohat' },
  { value: 'Abbottabad', label: 'Abbottabad' },
  { value: 'Bannu', label: 'Bannu' },
  { value: 'Mingora', label: 'Mingora' },
  { value: 'Swabi', label: 'Swabi' },
  { value: 'Charsadda', label: 'Charsadda' },
  { value: 'Chitral', label: 'Chitral' },
  { value: 'Hangu', label: 'Hangu' },
  { value: 'Kohistan', label: 'Kohistan' },
  { value: 'Kurram', label: 'Kurram' },
  { value: 'Lakki Marwat', label: 'Lakki Marwat' },
  { value: 'Malakand', label: 'Malakand' },
]
